/**
 * Shared read/merge/write for `public/assets/manifest.json`.
 *
 * The manifest is the single place the game learns what art exists. It is
 * written by two independent producers — `generate-assets` (procedural,
 * committed) and `fetch-assets` (downloaded, gitignored) — so each one
 * rewrites only the entries it owns, keyed by `origin`, and leaves the
 * other's alone.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
export const MANIFEST_PATH = join(ROOT, 'public', 'assets', 'manifest.json');
export const ATTRIBUTION_PATH = join(ROOT, 'public', 'assets', 'ATTRIBUTION.md');

export const EMPTY_MANIFEST = { version: 1, models: [] };

export async function loadManifest() {
  try {
    const raw = await readFile(MANIFEST_PATH, 'utf8');
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed.models)) return { ...EMPTY_MANIFEST };
    return { version: parsed.version ?? 1, models: parsed.models };
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
    return { ...EMPTY_MANIFEST };
  }
}

export async function saveManifest(manifest) {
  await mkdir(dirname(MANIFEST_PATH), { recursive: true });
  // Sort by id so two producers writing in different orders cannot create a
  // spurious diff.
  const models = [...manifest.models].sort((a, b) => a.id.localeCompare(b.id));
  await writeFile(MANIFEST_PATH, `${JSON.stringify({ ...manifest, models }, null, 2)}\n`, 'utf8');
}

/**
 * Replaces every entry with the given `origin`, keeping all others.
 *
 * This is what lets `assets:fetch` run without clobbering procedural assets,
 * and vice versa.
 */
export function replaceOrigin(manifest, origin, entries) {
  const kept = manifest.models.filter((model) => model.origin !== origin);
  return { ...manifest, models: [...kept, ...entries] };
}

/** Renders ATTRIBUTION.md from the manifest's licence metadata. */
export function renderAttribution(manifest) {
  const lines = [
    '# Asset attribution',
    '',
    '<!-- Generated by scripts/. Do not edit by hand: run `npm run assets:generate`',
    '     or `npm run assets:fetch` and commit the result. -->',
    '',
    'Every asset shipped with this project is listed here with its licence and',
    'origin. Assets under a licence that requires attribution (anything other',
    'than CC0 or public domain) **must** keep their credit line visible in the',
    'shipped game as well — see `docs/ASSETS.md`.',
    '',
  ];

  if (manifest.models.length === 0) {
    lines.push('_No assets are currently registered; the game runs on procedural geometry._');
    lines.push('');
    return lines.join('\n');
  }

  for (const model of [...manifest.models].sort((a, b) => a.id.localeCompare(b.id))) {
    const license = model.license ?? {};
    lines.push(`## \`${model.id}\``);
    lines.push('');
    lines.push(`- **File:** \`${model.url}\``);
    lines.push(`- **Licence:** ${license.name ?? 'UNKNOWN — must be filled in'}`);
    lines.push(`- **Source:** ${license.source ?? 'UNKNOWN — must be filled in'}`);
    if (license.author) lines.push(`- **Author:** ${license.author}`);
    if (model.description) lines.push(`- **Notes:** ${model.description}`);
    lines.push('');
  }

  return lines.join('\n');
}

export async function saveAttribution(manifest) {
  await mkdir(dirname(ATTRIBUTION_PATH), { recursive: true });
  await writeFile(ATTRIBUTION_PATH, renderAttribution(manifest), 'utf8');
}
