#!/usr/bin/env node
/**
 * Generates placeholder art procedurally.
 *
 * Why this exists: an agent can run `npm run assets:generate` and get real
 * glTF files with no network, no licence questions and no binary blobs to
 * review in a diff. The output is deterministic, so re-running it produces
 * byte-identical files and an unchanged git status.
 *
 * Everything here is a placeholder in the honest sense — the shapes are
 * readable at gameplay distance and nothing more. See `docs/ASSETS.md` for
 * how to replace them with real art.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { box, merge, toGltf } from './lib/gltf.mjs';
import {
  ROOT as root,
  loadManifest,
  replaceOrigin,
  saveAttribution,
  saveManifest,
} from './lib/manifest.mjs';

const outputDir = join(root, 'public', 'assets', 'generated');
const ORIGIN = 'generated';

/**
 * A blocky humanoid, 1.7 units tall and centred on the origin.
 *
 * Both properties matter to the renderer: the capsule it replaces spans
 * -0.85..+0.85 about the entity root, so a model built with its feet at y=0
 * would float half a body height above the floor. Forward is +Z, matching
 * `heading = atan2(vx, vz)` in the simulation.
 */
function runnerModel() {
  return merge([
    // Legs
    box({ center: [-0.15, -0.55, 0], size: [0.22, 0.6, 0.24] }),
    box({ center: [0.15, -0.55, 0], size: [0.22, 0.6, 0.24] }),
    // Torso
    box({ center: [0, 0.1, 0], size: [0.6, 0.7, 0.36] }),
    // Arms
    box({ center: [-0.39, 0.15, 0], size: [0.18, 0.6, 0.2] }),
    box({ center: [0.39, 0.15, 0], size: [0.18, 0.6, 0.2] }),
    // Head
    box({ center: [0, 0.65, 0], size: [0.42, 0.4, 0.4] }),
    // Visor on the +Z face: without it the model reads as symmetrical and you
    // cannot tell which way a player is facing.
    box({ center: [0, 0.68, 0.21], size: [0.3, 0.12, 0.04] }),
  ]);
}

/** A faceted crystal for pickups: two stacked pyramids, 0.8 units tall. */
function shardModel() {
  return merge([
    box({ center: [0, 0.12, 0], size: [0.3, 0.34, 0.3] }),
    box({ center: [0, 0.34, 0], size: [0.18, 0.22, 0.18] }),
    box({ center: [0, -0.14, 0], size: [0.18, 0.22, 0.18] }),
  ]);
}

/** A simple crate, useful as an obstacle or a prop. */
function crateModel() {
  return merge([
    box({ center: [0, 0, 0], size: [1, 1, 1] }),
    // Corner braces, so it does not read as an untextured cube.
    box({ center: [0, 0.5, 0], size: [1.06, 0.08, 1.06] }),
    box({ center: [0, -0.5, 0], size: [1.06, 0.08, 1.06] }),
  ]);
}

const MODELS = [
  {
    id: 'player',
    file: 'runner.gltf',
    build: runnerModel,
    baseColor: [0.72, 0.76, 0.86, 1],
    description: 'Blocky humanoid placeholder for player characters.',
  },
  {
    id: 'shard',
    file: 'shard.gltf',
    build: shardModel,
    baseColor: [0.96, 0.77, 0.09, 1],
    metallic: 0.35,
    roughness: 0.3,
    description: 'Faceted crystal placeholder for collectible pickups.',
  },
  {
    id: 'crate',
    file: 'crate.gltf',
    build: crateModel,
    baseColor: [0.55, 0.42, 0.28, 1],
    description: 'Braced crate placeholder for obstacles and props.',
  },
];

async function main() {
  await mkdir(outputDir, { recursive: true });

  const written = [];
  for (const model of MODELS) {
    const gltf = toGltf(model.build(), {
      name: model.id,
      baseColor: model.baseColor,
      ...(model.metallic !== undefined ? { metallic: model.metallic } : {}),
      ...(model.roughness !== undefined ? { roughness: model.roughness } : {}),
    });

    const path = join(outputDir, model.file);
    // Stable key order and a trailing newline keep re-runs diff-free.
    await writeFile(path, `${JSON.stringify(gltf, null, 2)}\n`, 'utf8');

    written.push({
      id: model.id,
      url: `assets/generated/${model.file}`,
      scale: 1,
      origin: ORIGIN,
      description: model.description,
      license: {
        name: 'CC0-1.0',
        source: 'Procedurally generated by scripts/generate-assets.mjs',
        author: 'fun-with-games contributors',
      },
    });
    console.log(`generated ${relative(root, path)}`);
  }

  const manifest = replaceOrigin(await loadManifest(), ORIGIN, written);
  await saveManifest(manifest);
  await saveAttribution(manifest);

  console.log(`\n${written.length} models written to ${relative(root, outputDir)}`);
  console.log('manifest.json and ATTRIBUTION.md updated');
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
